### ISSUE TITLE
first footnote doesn't seem to jump down

### ISSUE THREAD

**Issue by trashhalo** [MichaBrugger/obsidian-footnotes#2] opened 2022-03-07 12:31 UTC
The first time I press CMD-J (my shortcut) it creates ^1 on the line and adds a ^1 foot note but the cursor does not jump down to edit it. After that when I press CMD-J it adds ^2 and does jump to the right location.

I do have vim mode turned on. So not sure if related.

**Comment by MichaBrugger** [comment] 2022-03-07 12:56
As discussed on Discord: I'll look into it this weekend and come back to you asap!

@everyone else: If you experience the same issue, please leave a comment with your system specs and let me know if you have vim enabled or not. That would help a lot, thanks 👍🏼

**Comment by SYQsb** [comment] 2022-03-17 12:05
same here, cursor stays in the original position

configs: mba M1, Monterey 12.3; Obsidian version 0.13.33; plugin version 0.0.8

**Comment by queyuewutong** [comment] 2022-03-25 15:03
> The first time I press CMD-J (my shortcut) it creates ^1 on the line and adds a ^1 foot note but the cursor does not jump down to edit it. After that when I press CMD-J it adds ^2 and does jump to the right location.
> 
> I do have vim mode turned on. So not sure if related.



> The first time I press CMD-J (my shortcut) it creates ^1 on the line and adds a ^1 foot note but the cursor does not jump down to edit it. After that when I press CMD-J it adds ^2 and does jump to the right location.
> 
> I do have vim mode turned on. So not sure if related.

I ran into a similar problem. But I didn't open vim

**Comment by nihitkhandelwal-eng** [comment] 2022-03-27 03:44
I am also experiencing the same bug.
I am using Windows 10, Obsidian Version → v0.13.33, Vim not enabled

**Comment by nagapow** [comment] 2022-04-17 19:03
I have this same issue, i am using Mac v0.14.5... would be great if this can be fixed.

**Comment by MichaBrugger** [comment] 2022-04-17 19:43
Sorry for the long wait, I've been drowning in work lately. But I'll give my best to get to it before end of April.
Of course, a PR would be welcome too.

**Comment by MichaBrugger** [comment] 2022-04-23 12:06
I have done some testing with freshly set up vaults on two different systems (Windows 11 and Arch Linux) and somehow can't recreate the issue you're describing (Obsidian v0.14.6, installer version v0.12.10). Are there any more specifications you could give me that might allow me to identify the cause of the issue?

Has anyone tried this on a freshly set up vault? (There is always a chance it might be caused by some sort of interaction with another plugin)

**Comment by SYQsb** [comment] 2022-04-23 12:17
> 

I created a new vault and only installed this plug-in, then everything seems working fine.

my usual config(where the cursor problem occasionally exsits) is:  mba M1, Monterey 12.3; Obsidian version 0.13.33(vim disabled); plugin version 0.0.8
plug-in list: Copy as latex, footnote shortcut, shortcuts extender, table of contents, tag wrangler, underline

**Comment by MichaBrugger** [comment] 2022-04-23 12:21
Thanks for the quick reply! Have you generally tried to reinstall the plugin? I'll later also try to run it on my machines with the other plugins you mentioned (can't test iOS since I don't own a Mac).

**Comment by SYQsb** [comment] 2022-04-23 12:24
> Thanks for the quick reply! Have you generally tried to reinstall the plugin? I'll later also try to run it on my machines with the other plugins you mentioned (can't test iOS since I don't own a Mac).

sorry i made a mistake, the problem still exists in a new vault

**Comment by MichaBrugger** [comment] 2022-04-23 12:27
Ok! I'm suspecting it might be related to the installer version of Obsidian, but I will need to confirm that. I'll let you know as soon as I know more 👍🏼

**Comment by nagapow** [comment] 2022-04-24 05:54
this is really odd (good) - the problem has gone away!! i have tested it just now, both in a new vault and also in my old vault. The only different being i have the latest version 0.14.6, as opposed to 0.14.5 when i seeing the problem. I wonder if the obsidian app update has somehow corrected something?

**Comment by MichaBrugger** [comment] 2022-04-24 11:22
Thanks so much for that recording, that helps a lot! I will recreate your setup there and see if I can reproduce the bug. Once I can reproduce it, I'm pretty sure I can fix it too.

**Comment by MichaBrugger** [comment] 2022-04-25 10:56
@nagapow, I was able to reproduce the bug with your setup (thanks again for the recording). Unfortunately, I got a few exams this week, but I put in a blocker for the weekend, so by end of the week, it should be fixed 👍🏼

**Comment by nagapow** [comment] 2022-04-25 12:07
> 

Thank you for reviewing this - i am amazed by what you guys can do. Good luck with your exam, no rush and look forward to the update.

**Comment by krystoflp** [comment] 2022-04-28 19:39
I just came here to report the same issue to discover you've already managed to replicate it! :-) 
I use quite a lot of plugins for various reasons, but this one is the one I use for almost every note and has transformed my work - it really is a superb plugin. Thank you for writing it and working so hard to maintain it and get to the bottom of this issue.  👍

**Comment by svenluijten** [comment] 2022-06-03 21:35
From what I can see, this is because of [this line here](https://github.com/MichaBrugger/obsidian-footnotes/blob/master/main.ts#L198), the cursor cannot be set because Obsidian deems it "outside of [the] document":

![image](https://user-images.githubusercontent.com/11269635/171956043-f2c03c8a-bb96-4e1e-9349-a377a29aa784.jpeg)

Setting 2 breakpoints in the code while running the action on a (new) document confirms this, because the error only appears when I skip past the first breakpoint and hit the second one:

![image](https://user-images.githubusercontent.com/11269635/171956550-216392ec-361b-476f-b358-4ca4dd521375.jpeg)

---

I will try to do some more digging over the weekend, but the issue most certainly lies in the fact that Obsidian _thinks_ we're placing the cursor somewhere outside the document. Even though we aren't. Programming is fun 🙃

**Comment by nagapow** [comment] 2022-06-03 21:50
thanks for looking into this - sounds like from what you are saying this might be an Obsidian issue as opposed to the plugin itself.... could be a long wait for the fix?

**Comment by svenluijten** [comment] 2022-06-03 22:01
Not necessarily. I'm pretty sure there's a way for this plugin to work around it. But like I said, I'll see if I can make some time to look into it over the weekend 😄

**Comment by svenluijten** [comment] 2022-06-08 19:44
I've manually applied the patch in my `.obsidian` folder and it seems to work  nwo @MichaBrugger. Only thing it's not doing is inserting an empty line after my note. Here's a gif for context:

![obsidian](https://user-images.githubusercontent.com/11269635/172703664-73734b58-efda-48ab-91b4-e95a2f3931b3.gif)

I expected there to be an empty line after my final paragraph and the first footnote detail. However, this is a minor gripe, absolutely nothing that prevents this from being released imo 👍

**Comment by MichaBrugger** [comment] 2022-06-08 20:07
@svenluijten thanks for the quick feedback, that should be fixed now too 👍🏼

**Comment by nagapow** [comment] 2022-06-08 21:54
I tested on several of my files - it is working as expected 👍 thank you so much for fixing this, really grateful that you created this plugin, still using it daily.

**Comment by MichaBrugger** [comment] 2022-06-08 22:04
thanks for testing and your feedback. I will create a new release tomorrow 👍🏼

**Comment by svenluijten** [comment] 2022-06-11 19:07
Hi @MichaBrugger, have you been able to tag a release yet? 🙂

**Comment by Comprehensive-Jason** [comment] 2023-04-25 20:52
Is this still a problem for y'all, or is it fixed?

**Comment by svenluijten** [comment] 2023-04-28 07:47
This was already fixed, it just needed a release tagged. I just tested it on the latest stable version and it's not a problem anymore, so this issue can be closed!

**Closed** 2023-04-28 19:30 UTC
Labels: bug
